/*
 * Dialog_skins.java
 *
 * Created on __DATE__, __TIME__
 */

package forms;
import gestion_materiel.*;

import javax.swing.JFrame;
import javax.swing.filechooser.FileSystemView;
import javax.swing.tree.TreeNode;
import java.io.File;
import java.sql.ResultSet;

import org.jdesktop.swingx.treetable.FileSystemModel;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.MetalTheme;
import javax.swing.JDialog;
import com.l2fprod.gui.plaf.skin.Skin;
import com.l2fprod.gui.plaf.skin.SkinLookAndFeel;
import com.l2fprod.util.OS;
import com.l2fprod.gui.plaf.skin.Skin;
import com.l2fprod.gui.plaf.skin.SkinLookAndFeel;
import com.l2fprod.util.OS;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.MetalTheme;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;


/**
 *
 * @author  __USER__
 */
public class Dialog_skins extends javax.swing.JDialog {

    /** Creates new form Dialog_skins */
    MainForm m;
    
    public Dialog_skins(MainForm parent, boolean modal) {
        super(parent, modal);
        this.m = parent;
        initComponents();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("amarachthemepack.zip");
        jComboBox1.addItem("architectBluethemepack.zip");
        jComboBox1.addItem("architectOlivethemepack.zip");
        jComboBox1.addItem("b0sumiErgothempack.zip");
        jComboBox1.addItem("blueMetalthemepack.zip");
        jComboBox1.addItem("BeOSthemepack.zip");
        jComboBox1.addItem("bbjthemepack.zip");
        jComboBox1.addItem("b0sumithemepack.zip");
        jComboBox1.addItem("blueTurquesathemepack.zip");
        jComboBox1.addItem("cellshadedthemepack.zip");
        jComboBox1.addItem("chaNinja-Bluethemepack.zip");
        jComboBox1.addItem("coronaHthemepack.zip");
        jComboBox1.addItem("gfxOasisthemepack.zip");
        jComboBox1.addItem("fatalEthemepack.zip");
        jComboBox1.addItem("crystal2themepack.zip");
        jComboBox1.addItem("cougarthemepack.zip");

        Gbd gbd = new Gbd();
        gbd.connecter();
        String requete = "SELECT lnf FROM lnf";
        ResultSet r  = gbd.execQuery(requete);
        try
        {
        	r.next();
        	jComboBox1.setSelectedItem(r.getString("lnf"));
        	    
        }catch (Exception e){e.printStackTrace();}
        gbd.deconnecter();
        	        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel1.setText("Modification de l'apparence");

		jLabel2.setText("Choisissez un skins");

		jButton1.setText("Appliquer");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Annuler");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.add(31, 31, 31)
										.add(jLabel2)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel1)
														.add(
																jComboBox1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																160,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(113, 113, 113)).add(
								layout.createSequentialGroup().add(80, 80, 80)
										.add(jButton1).add(86, 86, 86).add(
												jButton2).addContainerGap(88,
												Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(jLabel1)
										.add(65, 65, 65)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel2)
														.add(
																jComboBox1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												60, Short.MAX_VALUE)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton1).add(
																jButton2)).add(
												56, 56, 56)));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	
	
	
	
	
	
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	 
	String themepack = "theme\\"+jComboBox1.getSelectedItem().toString();
      
      Gbd gbd = new Gbd();
      gbd.connecter();
      String requete = "UPDATE lnf SET lnf = '"+jComboBox1.getSelectedItem().toString()+"'";
      gbd.execUpdate(requete);
      gbd.deconnecter();
      
      try
      {
      if (themepack.endsWith(".xml")) {
        SkinLookAndFeel.setSkin(
          SkinLookAndFeel.loadThemePackDefinition(new File(themepack).toURL()));
        UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(m);
      } else if (themepack.startsWith("class:")) {
        String classname = themepack.substring("class:".length());
        SkinLookAndFeel.setSkin((Skin)Class.forName(classname).newInstance());
        UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(m);
      } else if (themepack.startsWith("theme:")) {
        String classname = themepack.substring("theme:".length());
        MetalTheme theme = (MetalTheme)Class.forName(classname).newInstance();
        MetalLookAndFeel metal = new MetalLookAndFeel();
        MetalLookAndFeel.setCurrentTheme(theme);
        UIManager.setLookAndFeel(metal);
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(m);
      } else {
        SkinLookAndFeel.setSkin(SkinLookAndFeel.loadThemePack(themepack));
        UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this);
        SwingUtilities.updateComponentTreeUI(m);
      }
        
      if (OS.isOneDotFourOrMore()) {
      java.lang.reflect.Method method =
        JFrame.class.getMethod(
          "setDefaultLookAndFeelDecorated",
          new Class[] { boolean.class });
      method.invoke(null, new Object[] { Boolean.TRUE });

      method =
        JDialog.class.getMethod(
          "setDefaultLookAndFeelDecorated",
          new Class[] { boolean.class });
      method.invoke(null, new Object[] { Boolean.TRUE });
      }
      }catch (Exception e)
      {
    	  e.printStackTrace();
      }
     
	 
	 
	 
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		this.setVisible(false);
	}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;

	private javax.swing.JButton jButton2;

	private javax.swing.JComboBox jComboBox1;

	private javax.swing.JLabel jLabel1;

	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}
