/*
 * Dialog_choixLogiciel.java
 *
 * Created on __DATE__, __TIME__
 */

package forms;

import gestion_materiel.Gbd;
import gestion_materiel.Logiciel;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jdesktop.swingx.JXErrorDialog;
import org.jdesktop.swingx.JXTable;
import org.jdesktop.swingx.decorator.AlternateRowHighlighter;
import org.jdesktop.swingx.decorator.Highlighter;
import org.jdesktop.swingx.decorator.HighlighterPipeline;
import org.jdesktop.swingx.decorator.RolloverHighlighter;

/**
 *
 * @author  __USER__
 */
public class Dialog_choixLogiciel extends javax.swing.JDialog {
	JXTable jTableL;
	DefaultTableModel model;
	Panel_logicielle p1;
	Vector v = new Vector();
	int id_pc;
    /** Creates new form Dialog_choixLogiciel */
    public Dialog_choixLogiciel(MainForm m, boolean modal,Panel_logicielle p,int id_pc) {
        super(m, modal);
        p1 = p;
model = new DefaultTableModel();
this.id_pc=id_pc;
    	
    	this.setName("Logiciels existants");
    	

    	model.addColumn("Id Logiciel");
    	model.addColumn("Nom ");
    	model.addColumn("Type");
    	
    	model.addColumn("System d exploitation");
    	model.addColumn("Memoire Ram Min");
    	model.addColumn("Memoire Carte Graphique Min");
    	model.addColumn("Espace Disque Min");
    	model.addColumn("Note Config Min");
    	
    //	this.m=m;
    	jTableL = new JXTable();
		jTableL.setHighlighters(
        new HighlighterPipeline(new Highlighter[] {AlternateRowHighlighter.quickSilver}));
		jTableL.setRolloverEnabled(true);
		jTableL.getHighlighters().addHighlighter(new RolloverHighlighter(Color.GRAY, Color.WHITE ));
		jTableL.setColumnControlVisible(true);
        
        
        initComponents();
        jBAnnuler.setText("Fermer");
        recupererLogiciels();
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jPanelTableau = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		//jTable1 = new javax.swing.JTable();
		jBAjouter = new javax.swing.JButton();
		jBAnnuler = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		jPanelTableau.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Logiciels"));
		jTableL.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null } },
				new String[] { "Nom", "Type", "System d exploitation",
						"Memoire Ram Min", "Memoire Carte Graphique Min",
						"Espace Disque Min", "Note Config Min" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTableL);

		org.jdesktop.layout.GroupLayout jPanelTableauLayout = new org.jdesktop.layout.GroupLayout(
				jPanelTableau);
		jPanelTableau.setLayout(jPanelTableauLayout);
		jPanelTableauLayout.setHorizontalGroup(jPanelTableauLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 924,
						Short.MAX_VALUE));
		jPanelTableauLayout.setVerticalGroup(jPanelTableauLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217,
						Short.MAX_VALUE));

		jBAjouter.setText("Ajouter");
		jBAjouter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBAjouterActionPerformed(evt);
			}
		});

		jBAnnuler.setText("Annuler");
		jBAnnuler.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBAnnulerActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap(332,
						Short.MAX_VALUE).add(jBAjouter).add(183, 183, 183).add(
						jBAnnuler).add(297, 297, 297)).add(
				layout.createSequentialGroup().add(jPanelTableau,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.add(
												jPanelTableau,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												19, Short.MAX_VALUE)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jBAjouter).add(
																jBAnnuler))
										.addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jBAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnnulerActionPerformed
	// TODO add your handling code here:
	this.dispose();
	
	}//GEN-LAST:event_jBAnnulerActionPerformed

	private void jBAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAjouterActionPerformed
	// TODO add your handling code here:
		int num = jTableL.getSelectedRow();
		
	
	  String ligne[]={jTableL.getValueAt(num, 0).toString(),
			  	jTableL.getValueAt(num, 1).toString(),
			  	jTableL.getValueAt(num, 2).toString(),
			  	jTableL.getValueAt(num, 3).toString(),
			  	jTableL.getValueAt(num, 4).toString(),
			  	jTableL.getValueAt(num, 5).toString(),
			  	jTableL.getValueAt(num, 6).toString(),
			  	jTableL.getValueAt(num, 7).toString()
	    };
	
	Logiciel l = new Logiciel();
	l.construireLogiciel(Integer.parseInt(jTableL.getValueAt(num, 0).toString()));

	Gbd gbd = new Gbd();
	String  requete="INSERT INTO installe_dans VALUES("+id_pc+","+Integer.parseInt(jTableL.getValueAt(num, 0).toString())+")";
	gbd.connecter();
	
	int res = gbd.execUpdate(requete);
	if(res==1)
	{p1.getModel().addRow(ligne);
	p1.getV().addElement(l);
	JOptionPane.showConfirmDialog(this, "Le Logiciel a été ajouté avec succès!","Ajout",JOptionPane.DEFAULT_OPTION);

	}
	else
		JOptionPane.showConfirmDialog(this, "Le Logiciel n a pas été ajouté !","Ajout",JOptionPane.ERROR_MESSAGE);
	//GEN-LAST:event_jBAjouterActionPerformed

	}  /**
    * @param args the command line arguments
    */
    
    public void recupererLogiciels()
    {
        	String requete ="";
        	
        	Gbd gbd = new Gbd();
        	gbd.connecter();
        	
        	requete  =  "SELECT id_logiciel FROM logiciel";
                	        	
        	ResultSet r = gbd.execQuery(requete);
        	
        	try{
        	
        		while (r.next())
        		{
        			Logiciel l = new Logiciel();
        			l.construireLogiciel((r.getInt("id_logiciel")));
        			v.add(l);
        		}
        	}catch (SQLException e)
        	{
        		e.printStackTrace();
        		JXErrorDialog.showDialog(null,"DataBase ERROR !!!",e);
        	}
        	
    Object [][] dataL = new Object[v.size()][8];
        	
        	
        	for (int i=0;i<v.size();i++)
        	{
        		Logiciel l =(Logiciel)v.elementAt(i);
        		dataL[i][0] = l.getId_logiciel().toString();
        		dataL[i][1] = l.getNom();
        		dataL[i][2] = l.getTypeLogicielle().getType();
        		dataL[i][3] = l.getCompatible().getNom_os();  
        		dataL[i][4] =  String.valueOf(l.getM_ram_min());
        		dataL[i][5] =  String.valueOf(l.getM_g_min());
        	    dataL[i][6] =  String.valueOf(l.getEspace_d_min());
        	    dataL[i][7] =  String.valueOf(l.getNote_config());
        	    	
        	    String ligne[]={l.getId_logiciel().toString(),
        	    		l.getNom(),
        	    		l.getTypeLogicielle().getType(),
        	    		l.getCompatible().getNom_os(),
        	    		String.valueOf(l.getM_ram_min()),
        	    		String.valueOf(l.getM_g_min()),
        	    		String.valueOf(l.getEspace_d_min()),
        	    		String.valueOf(l.getNote_config())
        	    };
        	    System.out.println(l.getId_logiciel().toString());
        	    
        	    model.addRow(ligne);
        	 }
        	jTableL.setModel(model);
        	
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jBAjouter;

	private javax.swing.JButton jBAnnuler;

	private javax.swing.JPanel jPanelTableau;

	private javax.swing.JScrollPane jScrollPane1;

	//private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}
