/*
 * Dialog_choixPc.java
 *
 * Created on __DATE__, __TIME__
 */

package forms;
import gestion_materiel.*;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.util.*;

/**
 *
 * @author  __USER__
 */
public class Dialog_choixPc extends javax.swing.JDialog {

    /** Creates new form Dialog_choixPc */
    
    MainForm m;
    Object [][] data=null;
    String [] titre={"id_pc","Marque","Modele","Numéro de série"};
    Vector v ;
    JPanel panel;
    public Dialog_choixPc(MainForm parent, boolean modal,JPanel panel) {
    	
    	
        super(parent, modal);
        
        this.panel = panel;
        
        
        initComponents();
        //this.setSize(500,300);
        
        this.m = parent;
        v= new Vector();
        
        
        System.out.println(parent.getName());
                
        String requete = "SELECT id_pc FROM PC";
        Gbd gbd = new Gbd();
        gbd.connecter();
        ResultSet r = gbd.execQuery(requete);
        int nombre = gbd.count();
        int i=0;
        data = new Object[nombre][4];
        
        if (nombre!=0)
        {
        	try
        	{
        		while(r.next())
        		{
        	
        			Pc p = new Pc();
        			p.construirePc(r.getInt("id_pc"));
        			
        			data[i][0] = p.getId_pc();
        			data[i][1] = p.getMarque();
        			data[i][2] = p.getModele();
        			data[i][3] = p.getNumero_serie();
        			i++;
        			
        			v.add(p);
        			
        			
        		}
        		gbd.deconnecter();
        	}catch(Exception e)
        	{
        		e.printStackTrace();
        	}
        
        	this.jTable1.setModel(getModel());
        
        }
}




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setModal(true);
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("Valider");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Annuler");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				242,
																				242,
																				242)
																		.add(
																				jButton1)
																		.add(
																				55,
																				55,
																				55)
																		.add(
																				jButton2))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				39,
																				39,
																				39)
																		.add(
																				jScrollPane1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				581,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(20, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												150,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton2).add(
																jButton1))
										.addContainerGap(13, Short.MAX_VALUE)));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		this.hide();
	}//GEN-LAST:event_jButton2ActionPerformed


	public TableModel getModel()
	{
	   
	   return new ModelJTable(data,titre);
   
	}



	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	 
		if (jTable1.getSelectedRowCount()!=0)
		{
		
					
			int i= jTable1.getSelectedRow();
			System.out.println(jTable1.getModel().getValueAt(i, 0));
			

	        if (panel instanceof Panel_intervention==false)
	        {
	        	Panel_peripherique p = (Panel_peripherique)this.m.jPanel1.getComponent(0);
	        	
	        	p.getTxtPc().setText(jTable1.getModel().getValueAt(i,1).toString()+" "+jTable1.getModel().getValueAt(i,2).toString());
	        	p.getCmbIdPc().removeAllItems();
	        	p.getCmbIdPc().addItem(" ");
	        	p.getCmbIdPc().addItem("Choisir un PC");
	        	p.getCmbIdPc().addItem(jTable1.getModel().getValueAt(i,0).toString());
	        	p.getCmbIdPc().setSelectedItem(jTable1.getModel().getValueAt(i,0).toString());
	        	Pc pc = (Pc)v.elementAt(i);
	        	p.getCmbIdLieu().addItem(pc.getLieu().getId_lieu());
	        	p.getCmbIdLieu().setSelectedItem(pc.getLieu().getId_lieu());
	        	p.getTxtTypeLieu().setText(pc.getLieu().getTypeLieu().getNom_type());
	        	System.out.println("LIEU=="+pc.getLieu().getNom());
	        	p.getTxtLieu().setText(pc.getLieu().getNom());
	        }
	        else
	        {
	        	
	        	Panel_intervention intervention = (Panel_intervention)this.panel;
	        	intervention.getCmbIdPc().removeAllItems();
	        	intervention.getCmbIdPc().addItem(" ");
	        	intervention.getCmbIdPc().addItem("Choisir un PC");
	        	intervention.getCmbIdPc().addItem(jTable1.getModel().getValueAt(i,0).toString());
	        	intervention.getCmbIdPc().setSelectedItem(jTable1.getModel().getValueAt(i,0).toString());
	        	intervention.getTxtNomPc().setText(jTable1.getModel().getValueAt(i,1).toString()+" "+jTable1.getModel().getValueAt(i,2).toString());
	        }
			
			
			this.setVisible(false);
			
		}
		
	}



// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;

	private javax.swing.JButton jButton2;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}
