/*
 * MainForm.java
 *
 * Created on __DATE__, __TIME__
 */

package forms;
import gestion_materiel.*;
import java.awt.BorderLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;
import javax.swing.*;
import java.io.File;
import java.sql.ResultSet;
import java.util.Locale;

import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import com.l2fprod.gui.plaf.skin.Skin;
import com.l2fprod.gui.plaf.skin.SkinLookAndFeel;
import com.l2fprod.util.OS;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.MetalTheme;

import org.jdesktop.swingx.JXTipOfTheDay;
import org.jdesktop.swingx.tips.DefaultTip;
import org.jdesktop.swingx.tips.DefaultTipOfTheDayModel;
import org.jdesktop.swingx.tips.TipOfTheDayModel.Tip;

/**
 *
 * @author  __USER__
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm()  {
        this.setName("Main form");
        this.setTitle("Gestion de matériel informatique");
    	this.setLocation(200, 30);
        initComponents();
        this.setSize(1000,760);
        //this.setResizable(false);
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		fichier = new javax.swing.JMenu();
		intervention = new javax.swing.JMenu();
		recherche = new javax.swing.JMenu();
		aide = new javax.swing.JMenu();
		inventaire = new javax.swing.JMenu(); 
		admin = new javax.swing.JMenu();
		soft = new JMenu();
		
		//Sous menu : PC
		pc = new javax.swing.JMenu("PC");
		listerPc = new javax.swing.JMenuItem("Lister les PC");
		
		//Sous menu : Peripherique
		peripherique = new javax.swing.JMenu("Périphérique");
		listerPeripherique = new javax.swing.JMenuItem("Lister les périphériques");

		//Sous menu: SOftwar
			logiciel = new JMenu();
			listerLogiciels = new JMenuItem();
		
		//Sous menu : Administration
		skins = new javax.swing.JMenuItem("Modifier l'apparence");
		network = new javax.swing.JMenuItem("Inventaire a distance");
		

//		Sous menu rechrche ajouter par mehdi
		rechrcheLogiciel = new JMenuItem("Rechrche de Logiciel");
		recherchePc = new JMenuItem("Recherche de PC");
		
		//Sous menu : Intervention
		javax.swing.JMenuItem listerIntervention = new javax.swing.JMenuItem("Afficher les interventions");
		
		
		quitter = new javax.swing.JMenuItem();
		
		

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 766,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 359,
				Short.MAX_VALUE));

		fichier.setText("Fichier");
		inventaire.setText("Hardware");
		inventaire.add(pc);
		listerPc.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				listerPcActionPerformed(e);
			}
		});
		
		pc.add(listerPc);
		
		
		intervention.add(listerIntervention);
		listerIntervention.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				interventionActionPerformed(e);
			}

			
		});
		
		
		quitter.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				quitterActionPerformed(e);
			}

			

			
		});
		
		inventaire.add(peripherique);
		listerPeripherique.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				listerPeripheriqueActionPerformed(e);
			}
		});
		
		
		
		listerLogiciels.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				listerLogicielsActionPerformed(e);
			}
		
		});
		peripherique.add(listerPeripherique);
		
		
		recherche.setText("Recherche");
		intervention.setText("Intervention");
		aide.setText("Aide");
		admin.setText("Administration");
		soft.setText("Software");//ajouter par mehdi
		logiciel.setText("Logiciels");
		listerLogiciels.setText("Lister les logiciel");
		logiciel.add(listerLogiciels);
		soft.add(logiciel);
		
		
		skins.addActionListener(new ActionListener(){
		
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				modifierApparence(e);
			}
		
		});
		
		network.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				InventaireADistanceActionPerformed(e);
			}
		});
		
		
		rechrcheLogiciel.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				rechrcheLogicielActionPerformed(e);
			}
		});
		
		recherchePc.addActionListener(new ActionListener(){
			public void actionPerformed(java.awt.event.ActionEvent e)
			{
				recherchePcActionPerformed(e);
			}
		});
		
		admin.add(skins);
		admin.add(network);
		
		quitter.setText("Quitter");
		fichier.add(quitter);
		jMenuBar1.add(fichier);
		jMenuBar1.add(inventaire);
		/// ajouter pa Mehdi
		jMenuBar1.add(soft);
		jMenuBar1.add(recherche);
		jMenuBar1.add(intervention);
		jMenuBar1.add(admin);
		jMenuBar1.add(aide);
		
		recherche.add(rechrcheLogiciel);
		recherche.add(recherchePc);

		setJMenuBar(jMenuBar1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(jPanel1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(39, 39, 39).add(jPanel1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).addContainerGap()));
		this.setSize(900,550);
//		
//		try {
//			UIManager.setLookAndFeel("skinlf.jar");
//			SwingUtilities.updateComponentTreeUI(this);
//		}
//		catch(Exception e) {
//			e.printStackTrace();
//		}

	}// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_jMenu1ActionPerformed
//GEN-LAST:event_jMenu1ActionPerformed
	
	
	
	private void quitterActionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		this.dispose();
		System.exit(0);
	}

	public void listerPeripheriqueActionPerformed(java.awt.event.ActionEvent e)
	{
		this.jPanel1.removeAll();
		this.jPanel1.repaint();
		
		Panel_peripherique p = new Panel_peripherique(this,-1);
		p.setSize(1000, 630);
		
		
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();
		
	}
////ajouter par mehdi
	public void listerLogicielsActionPerformed(java.awt.event.ActionEvent e)
	{
		this.jPanel1.removeAll();
		this.jPanel1.repaint();
		
		Panel_logicielle p = new Panel_logicielle(this,-1);
		p.setSize(1000, 600);
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();	
	}
	
	public void listerPcActionPerformed(java.awt.event.ActionEvent e)
	{
		this.jPanel1.removeAll();
		this.jPanel1.repaint();
		
		panelPc p = new panelPc(this,-1);
		p.setSize(1000, 600);
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();
		
	}
	
	public void rechrcheLogicielActionPerformed(java.awt.event.ActionEvent e)
	{
		this.jPanel1.removeAll();
		this.jPanel1.repaint();
		Panel_logicielle p = new Panel_logicielle(this,-2);
		p.setSize(1000, 600);
		
		
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();
	}
	public void modifierApparence(java.awt.event.ActionEvent e)
	{
//		this.jPanel1.removeAll();
//		this.jPanel1.repaint();
//		
//		Panel_skins p = new Panel_skins(this);
//		p.setSize(1000, 600);
//		this.jPanel1.add(BorderLayout.CENTER,p);
//		this.jPanel1.revalidate();
		
		Dialog_skins d = new Dialog_skins(this,true);
		d.pack();
		d.setSize(400,300);
		d.setLocationRelativeTo(this);
		d.setVisible(true);
		
	
	}
	
	private void interventionActionPerformed(ActionEvent e) {
	
		this.jPanel1.removeAll();
		this.jPanel1.repaint();
		
		Panel_intervention p = new Panel_intervention(this);
		p.setSize(1000, 600);
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();
		
		
	}
	
	
	public void InventaireADistanceActionPerformed(java.awt.event.ActionEvent e)
	{
		this.jPanel1.removeAll();
		this.jPanel1.repaint();
		
		Panel_Iad p = new Panel_Iad();
		p.setSize(1000, 600);
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();
	}
	
	public void recherchePcActionPerformed(java.awt.event.ActionEvent e)
	{	this.jPanel1.removeAll();
		this.jPanel1.repaint();
		panelPc p = new panelPc(this,-2);
		p.setSize(1000, 600);
		
		
		this.jPanel1.add(BorderLayout.CENTER,p);
		this.jPanel1.revalidate();
		
	}
		
	
	
    /**
    * @param args the command line arguments
    */
    public static void main (String args[])throws Exception {
        
      
      //Modifier le Look And Feel de l'application
    Gbd gbd = new Gbd();
    gbd.connecter();
    String requete = "SELECT lnf FROM lnf";
    ResultSet r  = gbd.execQuery(requete);
    r.next();
    String themepack = "theme\\"+r.getString("lnf");    
    gbd.deconnecter();	
    	
     
      if (themepack.endsWith(".xml")) {
        SkinLookAndFeel.setSkin(
          SkinLookAndFeel.loadThemePackDefinition(new File(themepack).toURL()));
        UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
      } else if (themepack.startsWith("class:")) {
        String classname = themepack.substring("class:".length());
        SkinLookAndFeel.setSkin((Skin)Class.forName(classname).newInstance());
        UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
      } else if (themepack.startsWith("theme:")) {
        String classname = themepack.substring("theme:".length());
        MetalTheme theme = (MetalTheme)Class.forName(classname).newInstance();
        MetalLookAndFeel metal = new MetalLookAndFeel();
        MetalLookAndFeel.setCurrentTheme(theme);
        UIManager.setLookAndFeel(metal);
      } else {
        SkinLookAndFeel.setSkin(SkinLookAndFeel.loadThemePack(themepack));
        UIManager.setLookAndFeel("com.l2fprod.gui.plaf.skin.SkinLookAndFeel");
      }
        
      if (OS.isOneDotFourOrMore()) {
      java.lang.reflect.Method method =
        JFrame.class.getMethod(
          "setDefaultLookAndFeelDecorated",
          new Class[] { boolean.class });
      method.invoke(null, new Object[] { Boolean.TRUE });

      method =
        JDialog.class.getMethod(
          "setDefaultLookAndFeelDecorated",
          new Class[] { boolean.class });
      method.invoke(null, new Object[] { Boolean.TRUE });
    }
    //Fin de modification du Look And Feel
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            	MainForm m = new MainForm();
            	    	
            	m.setVisible(true);
            	
            	//Creation des astuces du jour
            	DefaultTip t0=new DefaultTip("un","Vous pouvez effecuter des inventaires à distances" +
            			" sur des ordinateurs connectés au réseau à partir du sous menu Inventaire " +
            			"à distance du menu Administraion");
            	DefaultTip t1=new DefaultTip("deux","Pour ajouter des logiciels à un Pc, choisissez " +
            			"le menu Hardware->PC puis cliquer sur le bouton Logiciel");
            	DefaultTip t2=new DefaultTip("trois","Vous pouvez effectuer plusieurs recherches" +
            			" multicritères sur les Pc et les Logiciels à travers le menu Recherche");
            	DefaultTip t3=new DefaultTip("quatre","Vous pouvez voir les interventions qui ont " +
            			"été effectués sur un PC en cliquant sur le bouton Intervention de la fenetre Pc");
            	        
            	Tip tab[]=new Tip[4];
            	tab[0]=t0;
            	tab[1]=t1;
            	tab[2]=t2;
            	tab[3]=t3;
            	        
            	DefaultTipOfTheDayModel tipModel=new DefaultTipOfTheDayModel(tab);
            	        
            	JXTipOfTheDay tip=new JXTipOfTheDay();
            	tip.setModel(tipModel);
            	tip.setCurrentTip(2);
            	tip.showDialog(m);
                
                
                
            }
        });
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	
	//Declaration des menus
	private javax.swing.JMenu fichier;
	private javax.swing.JMenu inventaire;
	private javax.swing.JMenu soft ;
	private javax.swing.JMenu recherche;
	private javax.swing.JMenu intervention;
	private javax.swing.JMenu admin;
	private javax.swing.JMenu aide;
	
	//Declaration des sous_menus
	private javax.swing.JMenu pc;
	private javax.swing.JMenu logiciel ;// ajouter par mehdi
	private javax.swing.JMenu peripherique;
	
	private javax.swing.JMenuItem skins;
	private javax.swing.JMenuItem network;
	
	//Declaration des item qui composent les menus
		//PC
		private javax.swing.JMenuItem listerPc;
		private javax.swing.JMenuItem ajouterPc;
		private javax.swing.JMenuItem supprimerPc;
		private javax.swing.JMenuItem modifierPc;
	
		//Peripherique
		private javax.swing.JMenuItem listerPeripherique;
		private javax.swing.JMenuItem ajouterPeripherique;
		private javax.swing.JMenuItem supprimerPeripherique;
		private javax.swing.JMenuItem modifierPeripherique;
		
		//Logiciel ajouter par mehdi
		private javax.swing.JMenuItem listerLogiciels ;
	
		private javax.swing.JMenuItem rechrcheLogiciel;
	private javax.swing.JMenuItem quitter;

	private javax.swing.JMenuBar jMenuBar1;
	private JMenuItem recherchePc;

	javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}
